export { polygonClosureValidator } from './polygon-closure'
export { selfIntersectionValidator } from './self-intersection'
export { duplicateIdsValidator } from './duplicate-ids'
export { entranceConnectivityValidator } from './entrance-connectivity'
export { floorMetadataValidator } from './floor-metadata'
export { roadConnectivityValidator } from './road-connectivity'
export { referenceValidator } from './reference'
